<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form
    :model="formData"
    ref="vForm"
    :rules="rules"
    label-position="left"
    label-width="80px"
    size="default"
    @submit.prevent
  >
    <div class="card-container">
      <el-card style="width: 100% !important" shadow="never">
        <template #header>
          <div class="clear-fix">
            <span>藏品管理</span>
          </div>
        </template>
        <div class="static-content-item">
          <el-alert title="添加藏品" type="info" :closable="true" :center="true" :show-icon="true" effect="light" />
        </div>
        <div class="static-content-item">
          <div v-html="<b>html text</b>" />
        </div>
        <el-row>
          <el-col :span="8" class="grid-cell">
            <el-form-item label="主图" prop="main_image" class="required label-center-align">
              <el-upload
                :file-list="main_imageFileList"
                :headers="main_imageUploadHeaders"
                :data="main_imageUploadData"
                list-type="picture-card"
                show-file-list
                :limit="1"
              >
                <template #default><i class="el-icon-plus" /></template
              ></el-upload>
            </el-form-item>
          </el-col>
          <el-col :span="16" class="grid-cell">
            <el-form-item label="标题" prop="title" class="required label-center-align">
              <el-input v-model="formData.title" type="text" placeholder="请输入标题（32字符以内）" clearable />
            </el-form-item>
            <el-form-item label="副标题" prop="subtitle" class="required label-center-align">
              <el-input v-model="formData.subtitle" type="text" placeholder="请输入副标题（32字符以内）" clearable />
            </el-form-item>
            <el-form-item label="分类" prop="category" class="label-center-align">
              <el-select v-model="formData.category" class="full-width-input" clearable>
                <el-option
                  v-for="(item, index) in categoryOptions"
                  :key="index"
                  :label="item.label"
                  :value="item.value"
                  :disabled="item.disabled"
                />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>
        <el-form-item label="藏品描述" prop="description" class="required label-center-align">
          <el-input type="textarea" v-model="formData.description" rows="3" />
        </el-form-item>
        <el-form-item label="藏品介绍" prop="text" class="required label-center-align">
          <el-input type="textarea" v-model="formData.text" placeholder="请输入藏品介绍" rows="4" />
        </el-form-item>
      </el-card>
    </div>
  </el-form>
</template>

<script>
import { defineComponent, toRefs, reactive, getCurrentInstance } from "vue"
export default defineComponent({
  components: {},
  props: {},
  setup() {
    const state = reactive({
      formData: {
        main_image: null,
        title: "",
        subtitle: "",
        category: 1,
        description: "",
        text: ""
      },
      rules: {
        main_image: [
          {
            required: true,
            message: "字段值不可为空"
          }
        ],
        title: [
          {
            required: true,
            message: "字段值不可为空"
          }
        ],
        subtitle: [
          {
            required: true,
            message: "字段值不可为空"
          }
        ],
        description: [
          {
            required: true,
            message: "字段值不可为空"
          }
        ],
        text: [
          {
            required: true,
            message: "字段值不可为空"
          }
        ]
      },
      categoryOptions: [
        {
          label: "select 1",
          value: 1
        },
        {
          label: "select 2",
          value: 2
        },
        {
          label: "select 3",
          value: 3
        }
      ],
      main_imageFileList: [],
      main_imageUploadHeaders: {},
      main_imageUploadData: {}
    })
    const instance = getCurrentInstance()
    const submitForm = () => {
      instance.proxy.$refs["vForm"].validate((valid) => {
        if (!valid) return
        //TODO: 提交表单
      })
    }
    const resetForm = () => {
      instance.proxy.$refs["vForm"].resetFields()
    }
    return {
      ...toRefs(state),
      submitForm,
      resetForm
    }
  }
})
</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
  width: 100% !important;
}

.el-form-item--medium {
  .el-radio {
    line-height: 36px !important;
  }

  .el-rate {
    margin-top: 8px;
  }
}

.el-form-item--small {
  .el-radio {
    line-height: 32px !important;
  }

  .el-rate {
    margin-top: 6px;
  }
}

.el-form-item--mini {
  .el-radio {
    line-height: 28px !important;
  }

  .el-rate {
    margin-top: 4px;
  }
}

.clear-fix:before,
.clear-fix:after {
  display: table;
  content: "";
}

.clear-fix:after {
  clear: both;
}

.float-right {
  float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
  table.table-layout {
    width: 100%;
    table-layout: fixed;
    border-collapse: collapse;

    td.table-cell {
      display: table-cell;
      height: 36px;
      border: 1px solid #e1e2e3;
    }
  }
}

.label-left-align :deep(.el-form-item__label) {
  text-align: left;
}

.label-center-align :deep(.el-form-item__label) {
  text-align: center;
}

.label-right-align :deep(.el-form-item__label) {
  text-align: right;
}

.static-content-item {
  min-height: 20px;
  display: flex;
  align-items: center;

  :deep(.el-divider--horizontal) {
    margin: 0;
  }
}
</style>
